project:
  type: website
  output-dir: docs

website:
  title: "Travel 2024-2025"
  navbar:
    left:
      - href: index.qmd
        text: Destination
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

